version: '3.4'

services:
  petfamily.api:
    image: ${DOCKER_REGISTRY-}petfamilyapi
    build:
      context: .
      dockerfile: src/PetFamily.API/Dockerfile
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
     POSTGRES_DB: PetFamily
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    ports:
        - 5434:5432
    volumes:
        - postgres-data:/var/lib/postgressql/data
    
volumes:
     postgres-data:			  
