#version: '3.4'

services:
  petfamily.api:
    image: pet_family_api
    build:
      context: .
      dockerfile: src/PetFamily.API/Dockerfile
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
     POSTGRES_DB: PetFamily
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    ports:
        - 5434:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
        - ACCEPT_EULA=Y
    ports:
        - 5341:5341
        - 8081:80
    volumes:
        - seq:/var/lib/seq/data
   
volumes:
     postgres-data:	
        external: true
     seq:
        external: true